### ISSUE TITLE
Helpful fields to add

### ISSUE THREAD

**Issue by slothservice** [EtherTW/Terms#21]
1. The acronym field: Many terms have acronyms. For example, Externally owned accounts are EOA, and Proof of stake is POS. We should create a field for them.
2. Context field: We can add this field for the translator to add context or word choice rationale for the term.

**Comment by hmscheng** [comment]
Agreed. Adding an acronym field would be more search-friendly, and providing context allows people to understand the terms better.

**Comment by hmscheng** [comment]
Agreed. Adding an acronym field would be more search-friendly, and providing context allows people to understand the terms better.
