### ISSUE TITLE
Add basic CSS and javascript for the static webpage

### ISSUE THREAD

**Issue by antoncoding** [EtherTW/Terms#9]
## Objectives
* make the static webpage  more likeable 

## Styling
- [x] Change font
- [x] Align elements (put in the center)
- [x] Footer that link to TEM twitter

## Interaction
- [x] Search bar
- [x] Link to github for creating new issue (with an issue template to request translation for new terms)
- [ ] filtering based on tags

**Comment by ChihChengLiang** [comment]
Exposing the Telegram group link might be risky and adds much moderation effort. We should avoid adding the telegram link.
I like all the rest of the proposed features. Those sound so great!

**Comment by antoncoding** [comment]
updated it to link to twitter instead!
